# Generated by Django 5.2.1 on 2025-05-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_h2o', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% H2O')),
                ('tms', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ley_onz_tc', models.DecimalField(decimal_places=3, max_digits=10)),
                ('porcentaje_recuperacion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Recuperación')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ley',
                'verbose_name_plural': 'Leyes',
            },
        ),
    ]
