# Generated by Django 5.2.1 on 2025-05-13 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_muestra'),
        ('lotes', '0004_alter_lote_codigo_sistema_alter_lote_nro_sacos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ley',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Ley', 'verbose_name_plural': 'Leyes'},
        ),
        migrations.RemoveField(
            model_name='ley',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='ley',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='ley',
            name='usuario_modificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leyes_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='ley',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ley',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='ley',
            name='ley_onz_tc',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ley (onz/tc)'),
        ),
        migrations.AlterField(
            model_name='ley',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lote', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='ley',
            name='tms',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TMS'),
        ),
        migrations.AlterField(
            model_name='ley',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leyes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.DeleteModel(
            name='Muestra',
        ),
    ]
