# Generated by Django 5.2.1 on 2025-05-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pio_us_onza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maquila', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo_adicional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('analisis_newmonth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_analisis', models.CharField(choices=[('RW', 'RW'), ('RNW', 'RNW')], max_length=3)),
                ('analisis_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_usd_tms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humedad_lab', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tms_real', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ley_lab', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Costo',
                'verbose_name_plural': 'Costos',
            },
        ),
    ]
