# Generated by Django 5.2.1 on 2025-05-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costos', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costo',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
    ]
