# Generated by Django 5.2.1 on 2025-07-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='tipo_analisis',
            field=models.CharField(choices=[('NW', 'NW'), ('RE', 'RE'), ('RNW', 'RNW')], max_length=3),
        ),
    ]
