# Generated by Django 5.2.1 on 2025-07-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('balanza', 'Reporte de Balanza'), ('campanas', 'Reporte de Campañas'), ('lotes', 'Reporte de Lotes'), ('leyes', 'Reporte de Leyes'), ('costos', 'Reporte de Costos'), ('valorizaciones', 'Reporte de Valorizaciones'), ('liquidaciones', 'Reporte de Liquidaciones')], max_length=20),
        ),
    ]
