# Generated by Django 5.2.1 on 2025-05-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombres', models.CharField(max_length=200)),
                ('licencia_conducir', models.CharField(max_length=20)),
                ('categoria_licencia', models.CharField(max_length=10)),
                ('fecha_emision_licencia', models.DateField()),
                ('fecha_vencimiento_licencia', models.DateField()),
                ('direccion', models.TextField()),
                ('empresa', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='Facturador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('acopio', 'Acopio'), ('contrata', 'Contrata'), ('sociedad', 'Sociedad'), ('transportista', 'Transportista'), ('otro', 'Otro')], max_length=20)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Facturador',
                'verbose_name_plural': 'Facturadores',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('camion', 'Camión'), ('volquete', 'Volquete'), ('otro', 'Otro')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('facturador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='entidades.facturador')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='ProveedorIngemmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ingemmet', models.CharField(max_length=50)),
                ('procedencia', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('facturador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_ingemmet', to='entidades.facturador')),
            ],
            options={
                'verbose_name': 'Código Ingemmet',
                'verbose_name_plural': 'Códigos Ingemmet',
                'unique_together': {('facturador', 'codigo_ingemmet')},
            },
        ),
    ]
