# Generated by Django 5.2.1 on 2025-05-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proveedoringemmet',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='proveedoringemmet',
            name='facturador',
        ),
    ]
