# Generated by Django 5.2.1 on 2025-05-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_alter_proveedoringemmet_codigo_ingemmet_and_more'),
        ('entidades', '0004_alter_proveedoringemmet_codigo_ingemmet'),
    ]

    operations = [
    ]
