# Generated by Django 5.2.1 on 2025-05-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0005_merge_20250512_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturador',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='facturador',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturador',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
