# Generated by Django 5.2.1 on 2025-05-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_alter_vehiculo_marca_alter_vehiculo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
