# Generated by Django 5.2.1 on 2025-07-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0010_tipoproducto_es_mineral'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturador',
            name='banco',
            field=models.CharField(blank=True, choices=[('bcp', 'BCP'), ('interbank', 'Interbank'), ('caja_huancayo', 'Caja Huancayo'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='facturador',
            name='numero_cuenta_bancaria',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Cuenta Bancaria'),
        ),
    ]
