# Generated by Django 5.2.1 on 2025-07-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0011_facturador_banco_facturador_numero_cuenta_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturador',
            name='banco',
            field=models.CharField(blank=True, choices=[('bcp', 'Banco de Crédito del Perú (BCP)'), ('bbva', 'BBVA Perú'), ('interbank', 'Interbank'), ('scotiabank', 'Scotiabank Perú'), ('nacion', 'Banco de la Nación'), ('bbva_continental', 'Banco Continental (BBVA)'), ('pichincha', 'Banco Pichincha'), ('mibanco', 'Mibanco'), ('creditea', 'Creditea Perú'), ('banbif', 'BanBif'), ('falabella', 'Banco Falabella Perú'), ('banbif_interamericano', 'Banco Interamericano de Finanzas (BanBif)'), ('azteca', 'Banco Azteca'), ('gnb', 'Banco GNB'), ('otro', 'Otro')], max_length=50, null=True, verbose_name='Banco'),
        ),
    ]
