# Generated by Django 5.2.1 on 2025-07-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0012_alter_facturador_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturador',
            name='banco',
            field=models.CharField(blank=True, choices=[('bcp', 'BCP'), ('bbva', 'BBVA'), ('interbank', 'Interbank'), ('scotiabank', 'Scotiabank'), ('nacion', 'Nación'), ('pichincha', 'Pichincha'), ('mibanco', 'Mibanco'), ('creditea', 'Creditea'), ('banbif', 'BanBif'), ('falabella', 'Falabella'), ('azteca', 'Azteca'), ('gnb', 'GNB'), ('otro', 'Otro')], max_length=50, null=True, verbose_name='Banco'),
        ),
    ]
