# Generated by Django 5.2.1 on 2025-07-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0013_alter_facturador_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='categoria_licencia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='fecha_emision_licencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='fecha_vencimiento_licencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
