# Generated by Django 5.2.1 on 2025-05-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=100)),
                ('comprobante', models.CharField(max_length=100)),
                ('factura_nro', models.CharField(max_length=50)),
                ('pu_tmh_flete', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('finos_comercial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gramos_recuperados_comercial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorizacion_uds_tms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reintegro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neto_pagar_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anticipo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('neto_pagar_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detraccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banco', models.CharField(max_length=100)),
                ('cuenta', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lotes.lote')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Valorización',
                'verbose_name_plural': 'Valorizaciones',
            },
        ),
    ]
