# Generated by Django 5.2.1 on 2025-05-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorizacion',
            name='factura_nro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
