# Generated by Django 5.2.1 on 2025-05-12 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0009_tipoproducto'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('anulada', 'Anulada')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanas_creadas', to='usuarios.usuario')),
                ('usuario_modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campanas_modificadas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sistema', models.IntegerField()),
                ('codigo_lote', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('ruc', models.CharField(max_length=11)),
                ('procedencia', models.CharField(max_length=100)),
                ('tmh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guia_remision', models.CharField(max_length=50)),
                ('guia_transporte', models.CharField(max_length=50)),
                ('nro_sacos', models.IntegerField()),
                ('concesion', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('fecha_ley_agregada', models.DateTimeField(blank=True, null=True)),
                ('fecha_costo_agregado', models.DateTimeField(blank=True, null=True)),
                ('fecha_valorizacion_agregada', models.DateTimeField(blank=True, null=True)),
                ('fecha_liquidacion_agregada', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo_ingemmet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.proveedoringemmet')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.conductor')),
                ('facturador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.facturador')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.tipoproducto')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_transportados', to='entidades.facturador')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_creados', to='usuarios.usuario')),
                ('usuario_modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_modificados', to='usuarios.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.vehiculo')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='CampanaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.campana')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lote')),
            ],
            options={
                'verbose_name': 'Lote en Campaña',
                'verbose_name_plural': 'Lotes en Campañas',
                'unique_together': {('campana', 'lote')},
            },
        ),
    ]
