# Generated by Django 5.2.1 on 2025-05-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='codigo_sistema',
            field=models.CharField(choices=[('1', 'Producción propia'), ('2', 'Regalías'), ('3', 'Acopio'), ('5', 'Dispuesto contratas'), ('7', 'PAD')], max_length=1),
        ),
    ]
