# Generated by Django 5.2.1 on 2025-05-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_alter_lote_codigo_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='codigo_sistema',
            field=models.CharField(choices=[('1', '1-Producción propia'), ('2', '2-Regalías'), ('3', '3-Acopio'), ('5', '5-Descuento contratas'), ('7', '7-PAD')], max_length=1),
        ),
        migrations.AlterField(
            model_name='lote',
            name='nro_sacos',
            field=models.CharField(max_length=50, verbose_name='Nro sacos'),
        ),
    ]
