# Generated by Django 5.2.1 on 2025-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_alter_lote_codigo_sistema_alter_lote_nro_sacos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='tmh',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
