# Generated by Django 5.2.1 on 2025-05-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0009_tipoproducto'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia_ticket', models.CharField(max_length=20, unique=True)),
                ('lote_temporal', models.CharField(blank=True, max_length=50, null=True)),
                ('guia_remision', models.CharField(blank=True, max_length=50, null=True)),
                ('guia_transporte', models.CharField(blank=True, max_length=50, null=True)),
                ('peso_ingreso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_salida_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_neto_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.conductor')),
                ('facturador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.facturador')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.tipoproducto')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.vehiculo')),
            ],
            options={
                'verbose_name': 'Registro de Balanza',
                'verbose_name_plural': 'Registros de Balanza',
            },
        ),
    ]
