# Generated by Django 5.2.1 on 2025-07-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0003_balanza_cantidad_sacos_balanza_tipo_empaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanza',
            name='tipo_empaque',
            field=models.CharField(blank=True, choices=[('GRANEL', 'A GRANEL'), ('SACOS', 'SACOS')], max_length=10, null=True, verbose_name='Tipo carga mineral'),
        ),
    ]
