# Generated by Django 5.2.1 on 2025-05-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liquidaciones', '0001_initial'),
        ('lotes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_creadas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='usuario_modificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_modificadas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='liquidacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='liquidaciones.liquidacion'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lotes.lote'),
        ),
        migrations.AlterUniqueTogether(
            name='liquidaciondetalle',
            unique_together={('liquidacion', 'lote')},
        ),
    ]
