# Generated by Django 5.2.1 on 2025-05-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
